export const RECOMMENDED_PRODUCTS_IN_PROGRESS = "RECOMMENDED_PRODUCTS_IN_PROGRESS";
export const RECOMMENDED_PRODUCTS_SUCCESS = "RECOMMENDED_PRODUCTS_SUCCESS";
export const RECOMMENDED_PRODUCTS_ERROR = "RECOMMENDED_PRODUCTS_ERROR";

