export const ADMIN_ADD_PRODUCT_IN_PROGRESS = "ADMIN_ADD_PRODUCT_IN_PROGRESS";
export const ADMIN_ADD_PRODUCT_SUCCESS = "ADMIN_ADD_PRODUCT_SUCCESS";
export const ADMIN_ADD_PRODUCT_ERROR = "ADMIN_ADD_PRODUCT_ERROR";


export const ADMIN_EDIT_PRODUCT_IN_PROGRESS = "ADMIN_EDIT_PRODUCT_IN_PROGRESS";
export const ADMIN_EDIT_PRODUCT_SUCCESS = "ADMIN_EDIT_PRODUCT_SUCCESS";
export const ADMIN_EDIT_PRODUCT_ERROR = "ADMIN_EDIT_PRODUCT_ERROR";
