export const ADMIN_ORDERS_IN_PROGRESS = "ADMIN_ORDERS_IN_PROGRESS";
export const ADMIN_ORDERS_SUCCESS = "ADMIN_ORDERS_SUCCESS";
export const ADMIN_ORDERS_ERROR = "ADMIN_ORDERS_ERROR";
export const ADMIN_ORDERS_RESET = "ADMIN_ORDERS_RESET";



export const ADMIN_ORDER_DETAILS_IN_PROGRESS = "ADMIN_ORDER_DETAILS_IN_PROGRESS";
export const ADMIN_ORDER_DETAILS_SUCCESS = "ADMIN_ORDER_DETAILS_SUCCESS";
export const ADMIN_ORDER_DETAILS_ERROR = "ADMIN_ORDER_DETAILS_ERROR";


export const ADMIN_ORDER_FILTER = "ADMIN_ORDER_FILTER";