export const CART_IN_PROGRESS = "CART_IN_PROGRESS";
export const CART_SUCCESS = "CART_SUCCESS";
export const CART_ERROR = "CART_ERROR";

export const ADD_TO_CART_IN_PROGRESS = "ADD_TO_CART_IN_PROGRESS";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";


