export const NEW_ORDER_IN_PROGRESS = "NEW_ORDER_IN_PROGRESS";
export const NEW_ORDER_SUCCESS = "NEW_ORDER_SUCCESS";
export const NEW_ORDER_ERROR = "NEW_ORDER_ERROR";



export const USER_ORDERS_IN_PROGRESS = "USER_ORDERS_IN_PROGRESS";
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS";
export const USER_ORDERS_ERROR = "USER_ORDERS_ERROR";
export const USER_ORDERS_FILTER = "ADMIN_ORDER_FILTER";



export const USER_ORDER_DETAILS_IN_PROGRESS = "USER_ORDER_DETAILS_IN_PROGRESS";
export const USER_ORDER_DETAILS_SUCCESS = "USER_ORDER_DETAILS_SUCCESS";
export const USER_ORDER_DETAILS_ERROR = "USER_ORDER_DETAILS_ERROR";


