export const PRODUCTS_SEARCH_IN_PROGRESS = "PRODUCTS_SEARCH_IN_PROGRESS";
export const PRODUCTS_SEARCH_SUCCESS = "PRODUCTS_SEARCH_SUCCESS";
export const PRODUCTS_SEARCH_ERROR = "PRODUCTS_SEARCH_ERROR";
export const PRODUCTS_SEARCH_REDIRECT = "PRODUCTS_SEARCH_REDIRECT";


