export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN_IN_PROGRSS = "USER_LOGIN_IN_PROGRSS";
export const USER_LOGIN_SUCESS = "USER_LOGIN_SUCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";


export const VERIFY_TOKEN_IN_PROGRESS = "VERIFY_TOKEN_IN_PROGRESS";
export const VERIFY_TOKEN_SUCESS = "VERIFY_TOKEN_SUCESS";
export const VERIFY_TOKEN_FAILURE = "VERIFY_TOKEN_FAILURE";
export const VERIFY_TOKEN_ERROR = "VERIFY_TOKEN_ERROR";

export const USER_REGISTER_IN_PROGRSS = "USER_REGISTER_IN_PROGRSS";
export const USER_REGISTER_SUCESS = "USER_REGISTER_SUCESS";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

export const USER_INFO_IN_PROGRESS = "USER_INFO_IN_PROGRESS";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_ERROR = "USER_INFO_ERROR";

export const USER_CHANGE_EMAIL_IN_PROGRESS = "USER_CHANGE_EMAIL_IN_PROGRESS";
export const USER_CHANGE_EMAIL_SUCCESS = "USER_CHANGE_EMAIL_SUCCESS";
export const USER_CHANGE_EMAIL_ERROR = "USER_CHANGE_EMAIL_ERROR";

export const USER_CHANGE_PASSWORD_IN_PROGRESS = "USER_CHANGE_PASSWORD_IN_PROGRESS";
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS";
export const USER_CHANGE_PASSWORD_ERROR = "USER_CHANGE_PASSWORDL_ERROR";