export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN_IN_PROGRSS = "USER_LOGIN_IN_PROGRSS";
export const USER_LOGIN_SUCESS = "USER_LOGIN_SUCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";


export const VERIFY_TOKEN_IN_PROGRESS = "VERIFY_TOKEN_IN_PROGRESS";
export const VERIFY_TOKEN_SUCESS = "VERIFY_TOKEN_SUCESS";
export const VERIFY_TOKEN_FAILURE = "VERIFY_TOKEN_FAILURE";
export const VERIFY_TOKEN_ERROR = "VERIFY_TOKEN_ERROR";